// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gastos_divisiones.sql

package db

import (
	"context"
)

const countItemSplitsByItem = `-- name: CountItemSplitsByItem :one
SELECT COUNT(*)
FROM item_splits
WHERE item_id = $1
`

func (q *Queries) CountItemSplitsByItem(ctx context.Context, itemID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countItemSplitsByItem, itemID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createItemSplit = `-- name: CreateItemSplit :exec

INSERT INTO item_splits (
    item_id,
    user_id
) VALUES (
    $1,
    $2
)
ON CONFLICT (item_id, user_id) DO NOTHING
`

type CreateItemSplitParams struct {
	ItemID int32 `json:"item_id"`
	UserID int32 `json:"user_id"`
}

// ============================================================================
// DIVISIÓN DE GASTOS
// ============================================================================
func (q *Queries) CreateItemSplit(ctx context.Context, arg CreateItemSplitParams) error {
	_, err := q.db.ExecContext(ctx, createItemSplit, arg.ItemID, arg.UserID)
	return err
}

const createItemSplitsForAllUsers = `-- name: CreateItemSplitsForAllUsers :exec
INSERT INTO item_splits (
    item_id,
    user_id
)
SELECT $1, id FROM users
ON CONFLICT (item_id, user_id) DO NOTHING
`

func (q *Queries) CreateItemSplitsForAllUsers(ctx context.Context, itemID int32) error {
	_, err := q.db.ExecContext(ctx, createItemSplitsForAllUsers, itemID)
	return err
}

const deleteItemSplit = `-- name: DeleteItemSplit :exec
DELETE FROM item_splits
WHERE item_id = $1 AND user_id = $2
`

type DeleteItemSplitParams struct {
	ItemID int32 `json:"item_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteItemSplit(ctx context.Context, arg DeleteItemSplitParams) error {
	_, err := q.db.ExecContext(ctx, deleteItemSplit, arg.ItemID, arg.UserID)
	return err
}

const deleteItemSplitsByItem = `-- name: DeleteItemSplitsByItem :exec
DELETE FROM item_splits
WHERE item_id = $1
`

func (q *Queries) DeleteItemSplitsByItem(ctx context.Context, itemID int32) error {
	_, err := q.db.ExecContext(ctx, deleteItemSplitsByItem, itemID)
	return err
}

const getAllItemSplitsForPurchasedItems = `-- name: GetAllItemSplitsForPurchasedItems :many
SELECT 
    s.item_id,
    s.user_id
FROM item_splits s
INNER JOIN shopping_items si ON s.item_id = si.id
WHERE si.is_purchased = TRUE
`

func (q *Queries) GetAllItemSplitsForPurchasedItems(ctx context.Context) ([]ItemSplit, error) {
	rows, err := q.db.QueryContext(ctx, getAllItemSplitsForPurchasedItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemSplit
	for rows.Next() {
		var i ItemSplit
		if err := rows.Scan(&i.ItemID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemSplitsByItem = `-- name: ListItemSplitsByItem :many
SELECT 
    s.item_id,
    s.user_id,
    u.name AS user_name
FROM item_splits s
INNER JOIN users u ON s.user_id = u.id
WHERE s.item_id = $1
ORDER BY u.name ASC
`

type ListItemSplitsByItemRow struct {
	ItemID   int32  `json:"item_id"`
	UserID   int32  `json:"user_id"`
	UserName string `json:"user_name"`
}

func (q *Queries) ListItemSplitsByItem(ctx context.Context, itemID int32) ([]ListItemSplitsByItemRow, error) {
	rows, err := q.db.QueryContext(ctx, listItemSplitsByItem, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemSplitsByItemRow
	for rows.Next() {
		var i ListItemSplitsByItemRow
		if err := rows.Scan(&i.ItemID, &i.UserID, &i.UserName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
