// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lista_compras.sql

package db

import (
	"context"
	"database/sql"
)

const createShoppingItem = `-- name: CreateShoppingItem :one

INSERT INTO shopping_items (
    title,
    quantity
) VALUES (
    $1,
    $2
)
RETURNING id, title, quantity, price, is_purchased, paid_by_user_id, created_at
`

type CreateShoppingItemParams struct {
	Title    string `json:"title"`
	Quantity int32  `json:"quantity"`
}

// ============================================================================
// LISTA DE COMPRAS E HISTÓRICO
// ============================================================================
func (q *Queries) CreateShoppingItem(ctx context.Context, arg CreateShoppingItemParams) (ShoppingItem, error) {
	row := q.db.QueryRowContext(ctx, createShoppingItem, arg.Title, arg.Quantity)
	var i ShoppingItem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Quantity,
		&i.Price,
		&i.IsPurchased,
		&i.PaidByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteShoppingItem = `-- name: DeleteShoppingItem :exec
DELETE FROM shopping_items
WHERE id = $1
`

func (q *Queries) DeleteShoppingItem(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteShoppingItem, id)
	return err
}

const getShoppingItem = `-- name: GetShoppingItem :one
SELECT id, title, quantity, price, is_purchased, paid_by_user_id, created_at
FROM shopping_items
WHERE id = $1
`

func (q *Queries) GetShoppingItem(ctx context.Context, id int32) (ShoppingItem, error) {
	row := q.db.QueryRowContext(ctx, getShoppingItem, id)
	var i ShoppingItem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Quantity,
		&i.Price,
		&i.IsPurchased,
		&i.PaidByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingItems = `-- name: ListPendingItems :many
SELECT id, title, quantity, price, is_purchased, paid_by_user_id, created_at
FROM shopping_items
WHERE is_purchased = FALSE
ORDER BY created_at ASC
`

func (q *Queries) ListPendingItems(ctx context.Context) ([]ShoppingItem, error) {
	rows, err := q.db.QueryContext(ctx, listPendingItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShoppingItem
	for rows.Next() {
		var i ShoppingItem
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Quantity,
			&i.Price,
			&i.IsPurchased,
			&i.PaidByUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchasedItems = `-- name: ListPurchasedItems :many
SELECT id, title, quantity, price, is_purchased, paid_by_user_id, created_at
FROM shopping_items
WHERE is_purchased = TRUE
ORDER BY created_at DESC
`

func (q *Queries) ListPurchasedItems(ctx context.Context) ([]ShoppingItem, error) {
	rows, err := q.db.QueryContext(ctx, listPurchasedItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShoppingItem
	for rows.Next() {
		var i ShoppingItem
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Quantity,
			&i.Price,
			&i.IsPurchased,
			&i.PaidByUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchasedItemsWithPayer = `-- name: ListPurchasedItemsWithPayer :many
SELECT 
    si.id,
    si.title,
    si.quantity,
    si.price,
    si.is_purchased,
    si.paid_by_user_id,
    COALESCE(u.name, 'Desconocido')::varchar AS paid_by_user_name,
    si.created_at
FROM shopping_items si
LEFT JOIN users u ON si.paid_by_user_id = u.id
WHERE si.is_purchased = TRUE
ORDER BY si.created_at DESC
`

type ListPurchasedItemsWithPayerRow struct {
	ID             int32         `json:"id"`
	Title          string        `json:"title"`
	Quantity       int32         `json:"quantity"`
	Price          string        `json:"price"`
	IsPurchased    bool          `json:"is_purchased"`
	PaidByUserID   sql.NullInt32 `json:"paid_by_user_id"`
	PaidByUserName string        `json:"paid_by_user_name"`
	CreatedAt      sql.NullTime  `json:"created_at"`
}

func (q *Queries) ListPurchasedItemsWithPayer(ctx context.Context) ([]ListPurchasedItemsWithPayerRow, error) {
	rows, err := q.db.QueryContext(ctx, listPurchasedItemsWithPayer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPurchasedItemsWithPayerRow
	for rows.Next() {
		var i ListPurchasedItemsWithPayerRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Quantity,
			&i.Price,
			&i.IsPurchased,
			&i.PaidByUserID,
			&i.PaidByUserName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShoppingItems = `-- name: ListShoppingItems :many
SELECT id, title, quantity, price, is_purchased, paid_by_user_id, created_at
FROM shopping_items
ORDER BY created_at DESC
`

func (q *Queries) ListShoppingItems(ctx context.Context) ([]ShoppingItem, error) {
	rows, err := q.db.QueryContext(ctx, listShoppingItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShoppingItem
	for rows.Next() {
		var i ShoppingItem
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Quantity,
			&i.Price,
			&i.IsPurchased,
			&i.PaidByUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markItemAsPurchased = `-- name: MarkItemAsPurchased :one
UPDATE shopping_items
SET is_purchased = TRUE,
    price = $2,
    paid_by_user_id = $3
WHERE id = $1
RETURNING id, title, quantity, price, is_purchased, paid_by_user_id, created_at
`

type MarkItemAsPurchasedParams struct {
	ID           int32         `json:"id"`
	Price        string        `json:"price"`
	PaidByUserID sql.NullInt32 `json:"paid_by_user_id"`
}

func (q *Queries) MarkItemAsPurchased(ctx context.Context, arg MarkItemAsPurchasedParams) (ShoppingItem, error) {
	row := q.db.QueryRowContext(ctx, markItemAsPurchased, arg.ID, arg.Price, arg.PaidByUserID)
	var i ShoppingItem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Quantity,
		&i.Price,
		&i.IsPurchased,
		&i.PaidByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const unmarkItemAsPurchased = `-- name: UnmarkItemAsPurchased :one
UPDATE shopping_items
SET is_purchased = FALSE,
    price = 0.00,
    paid_by_user_id = NULL
WHERE id = $1
RETURNING id, title, quantity, price, is_purchased, paid_by_user_id, created_at
`

func (q *Queries) UnmarkItemAsPurchased(ctx context.Context, id int32) (ShoppingItem, error) {
	row := q.db.QueryRowContext(ctx, unmarkItemAsPurchased, id)
	var i ShoppingItem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Quantity,
		&i.Price,
		&i.IsPurchased,
		&i.PaidByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const updateShoppingItem = `-- name: UpdateShoppingItem :exec
UPDATE shopping_items
SET title = $2,
    quantity = $3
WHERE id = $1
`

type UpdateShoppingItemParams struct {
	ID       int32  `json:"id"`
	Title    string `json:"title"`
	Quantity int32  `json:"quantity"`
}

func (q *Queries) UpdateShoppingItem(ctx context.Context, arg UpdateShoppingItemParams) error {
	_, err := q.db.ExecContext(ctx, updateShoppingItem, arg.ID, arg.Title, arg.Quantity)
	return err
}
