// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type ItemSplit struct {
	ItemID int32 `json:"item_id"`
	UserID int32 `json:"user_id"`
}

type Settlement struct {
	ID         int32        `json:"id"`
	PayerID    int32        `json:"payer_id"`
	ReceiverID int32        `json:"receiver_id"`
	Amount     string       `json:"amount"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

type ShoppingItem struct {
	ID           int32         `json:"id"`
	Title        string        `json:"title"`
	Quantity     int32         `json:"quantity"`
	Price        string        `json:"price"`
	IsPurchased  bool          `json:"is_purchased"`
	PaidByUserID sql.NullInt32 `json:"paid_by_user_id"`
	CreatedAt    sql.NullTime  `json:"created_at"`
}

type User struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
}
