// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settlements.sql

package db

import (
	"context"
	"database/sql"
)

const createSettlement = `-- name: CreateSettlement :one

INSERT INTO settlements (
    payer_id,
    receiver_id,
    amount
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, payer_id, receiver_id, amount, created_at
`

type CreateSettlementParams struct {
	PayerID    int32  `json:"payer_id"`
	ReceiverID int32  `json:"receiver_id"`
	Amount     string `json:"amount"`
}

// ============================================================================
// DEUDAS Y TRANSFERENCIAS
// ============================================================================
func (q *Queries) CreateSettlement(ctx context.Context, arg CreateSettlementParams) (Settlement, error) {
	row := q.db.QueryRowContext(ctx, createSettlement, arg.PayerID, arg.ReceiverID, arg.Amount)
	var i Settlement
	err := row.Scan(
		&i.ID,
		&i.PayerID,
		&i.ReceiverID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSettlement = `-- name: DeleteSettlement :exec
DELETE FROM settlements
WHERE id = $1
`

func (q *Queries) DeleteSettlement(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteSettlement, id)
	return err
}

const getSettlement = `-- name: GetSettlement :one
SELECT 
    s.id,
    s.payer_id,
    p.name AS payer_name,
    s.receiver_id,
    r.name AS receiver_name,
    s.amount,
    s.created_at
FROM settlements s
INNER JOIN users p ON s.payer_id = p.id
INNER JOIN users r ON s.receiver_id = r.id
WHERE s.id = $1
`

type GetSettlementRow struct {
	ID           int32        `json:"id"`
	PayerID      int32        `json:"payer_id"`
	PayerName    string       `json:"payer_name"`
	ReceiverID   int32        `json:"receiver_id"`
	ReceiverName string       `json:"receiver_name"`
	Amount       string       `json:"amount"`
	CreatedAt    sql.NullTime `json:"created_at"`
}

func (q *Queries) GetSettlement(ctx context.Context, id int32) (GetSettlementRow, error) {
	row := q.db.QueryRowContext(ctx, getSettlement, id)
	var i GetSettlementRow
	err := row.Scan(
		&i.ID,
		&i.PayerID,
		&i.PayerName,
		&i.ReceiverID,
		&i.ReceiverName,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const getTotalPaidByUser = `-- name: GetTotalPaidByUser :one

SELECT COALESCE(SUM(price), 0.00)::numeric(10, 2) AS total_paid
FROM shopping_items
WHERE paid_by_user_id = $1 AND is_purchased = TRUE
`

// ============================================================================
// RESÚMENES Y BALANCE
// ============================================================================
func (q *Queries) GetTotalPaidByUser(ctx context.Context, paidByUserID sql.NullInt32) (string, error) {
	row := q.db.QueryRowContext(ctx, getTotalPaidByUser, paidByUserID)
	var total_paid string
	err := row.Scan(&total_paid)
	return total_paid, err
}

const getTotalSettlementsPaidByUser = `-- name: GetTotalSettlementsPaidByUser :one
SELECT COALESCE(SUM(amount), 0.00)::numeric(10, 2) AS total_paid
FROM settlements
WHERE payer_id = $1
`

func (q *Queries) GetTotalSettlementsPaidByUser(ctx context.Context, payerID int32) (string, error) {
	row := q.db.QueryRowContext(ctx, getTotalSettlementsPaidByUser, payerID)
	var total_paid string
	err := row.Scan(&total_paid)
	return total_paid, err
}

const getTotalSettlementsReceivedByUser = `-- name: GetTotalSettlementsReceivedByUser :one
SELECT COALESCE(SUM(amount), 0.00)::numeric(10, 2) AS total_received
FROM settlements
WHERE receiver_id = $1
`

func (q *Queries) GetTotalSettlementsReceivedByUser(ctx context.Context, receiverID int32) (string, error) {
	row := q.db.QueryRowContext(ctx, getTotalSettlementsReceivedByUser, receiverID)
	var total_received string
	err := row.Scan(&total_received)
	return total_received, err
}

const listAllSettlements = `-- name: ListAllSettlements :many
SELECT 
    s.id,
    s.payer_id,
    p.name AS payer_name,
    s.receiver_id,
    r.name AS receiver_name,
    s.amount,
    s.created_at
FROM settlements s
INNER JOIN users p ON s.payer_id = p.id
INNER JOIN users r ON s.receiver_id = r.id
ORDER BY s.created_at DESC
`

type ListAllSettlementsRow struct {
	ID           int32        `json:"id"`
	PayerID      int32        `json:"payer_id"`
	PayerName    string       `json:"payer_name"`
	ReceiverID   int32        `json:"receiver_id"`
	ReceiverName string       `json:"receiver_name"`
	Amount       string       `json:"amount"`
	CreatedAt    sql.NullTime `json:"created_at"`
}

func (q *Queries) ListAllSettlements(ctx context.Context) ([]ListAllSettlementsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllSettlements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllSettlementsRow
	for rows.Next() {
		var i ListAllSettlementsRow
		if err := rows.Scan(
			&i.ID,
			&i.PayerID,
			&i.PayerName,
			&i.ReceiverID,
			&i.ReceiverName,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettlementsBetweenUsers = `-- name: ListSettlementsBetweenUsers :many
SELECT 
    s.id,
    s.payer_id,
    p.name AS payer_name,
    s.receiver_id,
    r.name AS receiver_name,
    s.amount,
    s.created_at
FROM settlements s
INNER JOIN users p ON s.payer_id = p.id
INNER JOIN users r ON s.receiver_id = r.id
WHERE (s.payer_id = $1 AND s.receiver_id = $2)
   OR (s.payer_id = $2 AND s.receiver_id = $1)
ORDER BY s.created_at DESC
`

type ListSettlementsBetweenUsersParams struct {
	PayerID    int32 `json:"payer_id"`
	ReceiverID int32 `json:"receiver_id"`
}

type ListSettlementsBetweenUsersRow struct {
	ID           int32        `json:"id"`
	PayerID      int32        `json:"payer_id"`
	PayerName    string       `json:"payer_name"`
	ReceiverID   int32        `json:"receiver_id"`
	ReceiverName string       `json:"receiver_name"`
	Amount       string       `json:"amount"`
	CreatedAt    sql.NullTime `json:"created_at"`
}

func (q *Queries) ListSettlementsBetweenUsers(ctx context.Context, arg ListSettlementsBetweenUsersParams) ([]ListSettlementsBetweenUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listSettlementsBetweenUsers, arg.PayerID, arg.ReceiverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSettlementsBetweenUsersRow
	for rows.Next() {
		var i ListSettlementsBetweenUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.PayerID,
			&i.PayerName,
			&i.ReceiverID,
			&i.ReceiverName,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
